### ISSUE TITLE
Session instances don't unload from memory

### ISSUE THREAD

**Issue by DmitryRomanenko** [bloomberg/blpapi-node#21]
When session can't connect to server, it hangs. To prevent it we may create new instance of session but old versions won't unload from memory.
Is there any way to reconnect using existing session?

Here is a small code example:

    var config = { serverHost: '127.0.0.1', serverPort: 8199 }; // INCORRECT(!!!) IP
    var seclist = ['GXG4 Index', 'GXG4 Comdty'];
    
    var blpapi = require('blpapi');
    var session = new blpapi.Session(config);
    var service_refdata = 1;
    
    var responses = 0;
    function checkStop() {
        responses++;
        if (responses == 1)
            session.stop();
    }
    
    session.on('SessionStarted', function(m) {
        console.log('SessionStarted');
        session.openService('//blp/refdata', service_refdata);
    });
    session.on('ServiceOpened', function(m) {
        console.log('ServiceOpened');
        if (m.correlations[0].value == service_refdata) {
            session.request('//blp/refdata', 'ReferenceDataRequest',
                { securities: seclist, fields: ['NAME', 'TICKER'] }, 100);
        }
    });
    session.on('ReferenceDataResponse', function(m) {
        console.log(JSON.stringify(m));
        if (m.correlations[0].value === 100 && m.eventType === 'RESPONSE')
            checkStop();
    });
    session.on('SessionTerminated', function(m) {
        console.log('destroy');
        session.destroy();
    });
    
    console.log('starting...');
    session.start();

**Comment by apaprocki** [comment]
Assuming the issue is resolved now.
