### ISSUE TITLE
access to BDH bloomberg historical data via blpapi-node?

### ISSUE THREAD

**Issue by mahalamobile** [bloomberg/blpapi-node#36]
Hi guys

Im trying to get the historical data of JIBRA 3M, now you can do this in excel but i require this as a service, any help appreciated?! see below

=BDH("JIBA3M Index","last price","20150127","20150127")
=bdh("ticker","field","start date","end date")

**Comment by apaprocki** [comment]
There is a historical data request sample that should show you how to do what you're asking. This is just a module for hitting BLPAPI via Node. Historical data requests are available via any of the supported languages. I suggest reading the [BLPAPI Developer Guide](http://www.bloomberglabs.com/api/documentation/) for more information. Let me know if that answers the question for you.

**Comment by mahalamobile** [comment]
cool thanks
