### ISSUE TITLE
blpapo_root

### ISSUE THREAD

**Issue by gatorockero** [bloomberg/blpapi-node#38]
Hi, im traying to install the blpapi, but i need set blpapi_root like a enviromental variable, i have a mac, any help please?

**Comment by apaprocki** [comment]
Can you please post the entire exact error message you are seeing in your terminal?

**Comment by gatorockero** [comment]
Hi, i solve the problem with the previous post.
Thanks a lot!!

2015-02-26 0:09 GMT-03:00 Andrew Paprocki <notifications@github.com>:

> Can you please post the entire exact error message you are seeing in your
> terminal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bloomberg/blpapi-node/issues/38#issuecomment-76114772>
> .
>



-- 
Atte
Gustavo
