### ISSUE TITLE
How I can get all the ISIN list from RblpAPI?

### ISSUE THREAD

**Issue by bushiyundeyu** [bloomberg/blpapi-node#70]
Hi,
    Is there anybody to know how I can get all the ISIN list by this API? I see that I can get the details by /isin/XXXXXXXXX. But for now I want get all the ISIN first.

**Comment by ericvw** [comment]
@bushiyundeyu, I would recommend reading Bloomberg's [BLPAPI's Developer Guide](http://www.bloomberglabs.com/api/documentation/).  This issue isn't particular to the NodeJS bindings/wrapper itself.
